games_played:
  achiupr01:
    estimated: true
    gp: 82
  adamsst01:
    estimated: true
    gp: 82
  adebaba01:
    estimated: true
    gp: 82
  aldamsa01:
    estimated: true
    gp: 82
  alexani01:
    estimated: true
    gp: 82
  alexatr01:
    estimated: true
    gp: 82
  allengr01:
    estimated: true
    gp: 82
  allenja01:
    estimated: true
    gp: 82
  alvarjo01:
    estimated: true
    gp: 82
  anderky01:
    estimated: true
    gp: 82
  antetgi01:
    estimated: true
    gp: 82
  anunoog01:
    estimated: true
    gp: 82
  avdijde01:
    estimated: true
    gp: 82
  aytonde01:
    estimated: true
    gp: 82
  baglema01:
    estimated: true
    gp: 82
  baileac01:
    estimated: true
    gp: 82
  ballla01:
    estimated: true
    gp: 82
  bambamo01:
    estimated: true
    gp: 82
  banchpa01:
    estimated: true
    gp: 82
  banede01:
    estimated: true
    gp: 82
  barlodo01:
    estimated: true
    gp: 82
  barneha02:
    estimated: true
    gp: 82
  barnesc01:
    estimated: true
    gp: 82
  barnhbr01:
    estimated: true
    gp: 82
  barrerj01:
    estimated: true
    gp: 82
  bassech01:
    estimated: true
    gp: 82
  battlja01:
    estimated: true
    gp: 82
  bealbr01:
    estimated: true
    gp: 82
  berinjo01:
    estimated: true
    gp: 82
  beysa01:
    estimated: true
    gp: 82
  bitadgo01:
    estimated: true
    gp: 82
  blackan01:
    estimated: true
    gp: 82
  bogdabo01:
    estimated: true
    gp: 82
  bonaad01:
    estimated: true
    gp: 82
  bookede01:
    estimated: true
    gp: 82
  bouyeja01:
    estimated: true
    gp: 82
  braunch01:
    estimated: true
    gp: 82
  breako01:
    estimated: true
    gp: 82
  bridgmi01:
    estimated: true
    gp: 82
  bridgmi02:
    estimated: true
    gp: 82
  brookdi01:
    estimated: true
    gp: 82
  broomjo01:
    estimated: true
    gp: 82
  brownja02:
    estimated: true
    gp: 82
  brownko01:
    estimated: true
    gp: 82
  brunsja01:
    estimated: true
    gp: 82
  bryanca01:
    estimated: true
    gp: 82
  bryanth01:
    estimated: true
    gp: 82
  bufkiko01:
    estimated: true
    gp: 82
  butleji01:
    estimated: true
    gp: 82
  buzelma01:
    estimated: true
    gp: 82
  cainja01:
    estimated: true
    gp: 82
  caldwke01:
    estimated: true
    gp: 82
  camarto01:
    estimated: true
    gp: 82
  capelca01:
    estimated: true
    gp: 82
  cardwdy01:
    estimated: true
    gp: 82
  carlsbr01:
    estimated: true
    gp: 82
  carrica01:
    estimated: true
    gp: 82
  cartede02:
    estimated: true
    gp: 82
  carteje01:
    estimated: true
    gp: 82
  cartewe01:
    estimated: true
    gp: 82
  carusal01:
    estimated: true
    gp: 82
  castlco01:
    estimated: true
    gp: 82
  castlst01:
    estimated: true
    gp: 82
  champju01:
    estimated: true
    gp: 82
  champju02:
    estimated: true
    gp: 82
  chrisca02:
    estimated: true
    gp: 82
  chrisma02:
    estimated: true
    gp: 82
  cissosi01:
    estimated: true
    gp: 82
  clarkja02:
    estimated: true
    gp: 82
  clarkjo01:
    estimated: true
    gp: 82
  claxtni01:
    estimated: true
    gp: 82
  claytwa01:
    estimated: true
    gp: 82
  cliffni01:
    estimated: true
    gp: 82
  clingdo01:
    estimated: true
    gp: 82
  clownno01:
    estimated: true
    gp: 82
  colliis01:
    estimated: true
    gp: 82
  collijo01:
    estimated: true
    gp: 82
  colliza01:
    estimated: true
    gp: 82
  conlemi01:
    estimated: true
    gp: 82
  connapa01:
    estimated: true
    gp: 82
  coulibi01:
    estimated: true
    gp: 82
  cowarce01:
    estimated: true
    gp: 82
  crawfis01:
    estimated: true
    gp: 82
  cryerlj01:
    estimated: true
    gp: 82
  cunnica01:
    estimated: true
    gp: 82
  curryst01:
    estimated: true
    gp: 82
  dadiepa01:
    estimated: true
    gp: 82
  daniedy01:
    estimated: true
    gp: 82
  dasiltr01:
    estimated: true
    gp: 82
  davisan02:
    estimated: true
    gp: 82
  demineg01:
    estimated: true
    gp: 82
  dennira01:
    estimated: true
    gp: 82
  diabamo01:
    estimated: true
    gp: 82
  diawamo01:
    estimated: true
    gp: 82
  dickgr01:
    estimated: true
    gp: 82
  diengou01:
    estimated: true
    gp: 82
  dilliro01:
    estimated: true
    gp: 82
  divindo01:
    estimated: true
    gp: 82
  doncilu01:
    estimated: true
    gp: 82
  dortlu01:
    estimated: true
    gp: 82
  dosunay01:
    estimated: true
    gp: 82
  drumman01:
    estimated: true
    gp: 82
  dunnkr01:
    estimated: true
    gp: 82
  dunnry01:
    estimated: true
    gp: 82
  duranke01:
    estimated: true
    gp: 82
  easonta01:
    estimated: true
    gp: 82
  edeyza01:
    estimated: true
    gp: 82
  edgecvj01:
    estimated: true
    gp: 82
  edwaran01:
    estimated: true
    gp: 82
  edwarju01:
    estimated: true
    gp: 82
  elliske01:
    estimated: true
    gp: 82
  embiijo01:
    estimated: true
    gp: 82
  enarutr01:
    estimated: true
    gp: 82
  essenno01:
    estimated: true
    gp: 82
  fearsje01:
    estimated: true
    gp: 82
  filipky01:
    estimated: true
    gp: 82
  finnedo01:
    estimated: true
    gp: 82
  flaggco01:
    estimated: true
    gp: 82
  flaglad01:
    estimated: true
    gp: 82
  flemira01:
    estimated: true
    gp: 82
  fontesi01:
    estimated: true
    gp: 82
  foxde01:
    estimated: true
    gp: 82
  freemen01:
    estimated: true
    gp: 82
  furphjo01:
    estimated: true
    gp: 82
  gaffoda01:
    estimated: true
    gp: 82
  gardnmy01:
    estimated: true
    gp: 82
  garlada01:
    estimated: true
    gp: 82
  garzalu01:
    estimated: true
    gp: 82
  georgke01:
    estimated: true
    gp: 82
  georgky01:
    estimated: true
    gp: 82
  georgpa01:
    estimated: true
    gp: 82
  gibsota01:
    estimated: true
    gp: 82
  giddejo01:
    estimated: true
    gp: 82
  gilbeke01:
    estimated: true
    gp: 82
  gilgesh01:
    estimated: true
    gp: 82
  gilleco01:
    estimated: true
    gp: 82
  goberru01:
    estimated: true
    gp: 82
  goldivl01:
    estimated: true
    gp: 82
  gonzahu01:
    estimated: true
    gp: 82
  goodwjo01:
    estimated: true
    gp: 82
  gordoaa01:
    estimated: true
    gp: 82
  greenaj01:
    estimated: true
    gp: 82
  greendr01:
    estimated: true
    gp: 82
  greenja02:
    estimated: true
    gp: 82
  greenja05:
    estimated: true
    gp: 82
  greenjo02:
    estimated: true
    gp: 82
  grimequ01:
    estimated: true
    gp: 82
  gueyemo02:
    estimated: true
    gp: 82
  halibty01:
    estimated: true
    gp: 82
  hallpj01:
    estimated: true
    gp: 82
  hardati02:
    estimated: true
    gp: 82
  hardeja01:
    estimated: true
    gp: 82
  hardyja02:
    estimated: true
    gp: 82
  harpedy01:
    estimated: true
    gp: 82
  harpero02:
    estimated: true
    gp: 82
  harriga01:
    estimated: true
    gp: 82
  harrito02:
    estimated: true
    gp: 82
  harteis01:
    estimated: true
    gp: 82
  hartjo01:
    estimated: true
    gp: 82
  hausesa01:
    estimated: true
    gp: 82
  hayesja02:
    estimated: true
    gp: 82
  hendesc01:
    estimated: true
    gp: 82
  hendrta01:
    estimated: true
    gp: 82
  hepbuch01:
    estimated: true
    gp: 82
  herroty01:
    estimated: true
    gp: 82
  hieldbu01:
    estimated: true
    gp: 82
  highsha01:
    estimated: true
    gp: 82
  hinsobl01:
    estimated: true
    gp: 82
  holidjr01:
    estimated: true
    gp: 82
  hollaro01:
    estimated: true
    gp: 82
  holmeda01:
    estimated: true
    gp: 82
  holmgch01:
    estimated: true
    gp: 82
  horfoal01:
    estimated: true
    gp: 82
  howarje01:
    estimated: true
    gp: 82
  huertke01:
    estimated: true
    gp: 82
  huffja01:
    estimated: true
    gp: 82
  hukpoar01:
    estimated: true
    gp: 82
  huntede01:
    estimated: true
    gp: 82
  huntlcj01:
    estimated: true
    gp: 82
  hylanbo01:
    estimated: true
    gp: 82
  ighodos01:
    estimated: true
    gp: 82
  ingrabr01:
    estimated: true
    gp: 82
  ingraha01:
    estimated: true
    gp: 82
  irvinky01:
    estimated: true
    gp: 82
  isaacjo01:
    estimated: true
    gp: 82
  jacksan01:
    estimated: true
    gp: 82
  jacksgg01:
    estimated: true
    gp: 82
  jacksis01:
    estimated: true
    gp: 82
  jacksja02:
    estimated: true
    gp: 82
  jacksqu01:
    estimated: true
    gp: 82
  jackstr02:
    estimated: true
    gp: 82
  jakucka01:
    estimated: true
    gp: 82
  jamesbr02:
    estimated: true
    gp: 82
  jamesle01:
    estimated: true
    gp: 82
  jamessi01:
    estimated: true
    gp: 82
  jaqueja01:
    estimated: true
    gp: 82
  jemistr01:
    estimated: true
    gp: 82
  jenkida01:
    estimated: true
    gp: 82
  jeromty01:
    estimated: true
    gp: 82
  joeis01:
    estimated: true
    gp: 82
  johnsca02:
    estimated: true
    gp: 82
  johnsch06:
    estimated: true
    gp: 82
  johnsja05:
    estimated: true
    gp: 82
  johnske04:
    estimated: true
    gp: 82
  johnske10:
    estimated: true
    gp: 82
  johnstr03:
    estimated: true
    gp: 82
  jokicni01:
    estimated: true
    gp: 82
  jonesda06:
    estimated: true
    gp: 82
  jonesde02:
    estimated: true
    gp: 82
  joneshe01:
    estimated: true
    gp: 82
  joneska03:
    estimated: true
    gp: 82
  jonessp01:
    estimated: true
    gp: 82
  jonestr01:
    estimated: true
    gp: 82
  jonesty01:
    estimated: true
    gp: 82
  jordade01:
    estimated: true
    gp: 82
  jovicni01:
    estimated: true
    gp: 82
  kalkbry01:
    estimated: true
    gp: 82
  kennalu01:
    estimated: true
    gp: 82
  kentja01:
    estimated: true
    gp: 82
  kesslwa01:
    estimated: true
    gp: 82
  kispeco01:
    estimated: true
    gp: 82
  knechda01:
    estimated: true
    gp: 82
  knuepko01:
    estimated: true
    gp: 82
  kolekty01:
    estimated: true
    gp: 82
  kolokch01:
    estimated: true
    gp: 82
  konanya01:
    estimated: true
    gp: 82
  kornelu01:
    estimated: true
    gp: 82
  krejcvi01:
    estimated: true
    gp: 82
  kuminjo01:
    estimated: true
    gp: 82
  kuzmaky01:
    estimated: true
    gp: 82
  landajo01:
    estimated: true
    gp: 82
  laravja01:
    estimated: true
    gp: 82
  larsspe01:
    estimated: true
    gp: 82
  lavinza01:
    estimated: true
    gp: 82
  leonaka01:
    estimated: true
    gp: 82
  leonsma01:
    estimated: true
    gp: 82
  leverca01:
    estimated: true
    gp: 82
  lillada01:
    estimated: true
    gp: 82
  livelde01:
    estimated: true
    gp: 82
  looneke01:
    estimated: true
    gp: 82
  lopezbr01:
    estimated: true
    gp: 82
  loveca01:
    estimated: true
    gp: 82
  lylestr01:
    estimated: true
    gp: 82
  maluakh01:
    estimated: true
    gp: 82
  mamuksa01:
    estimated: true
    gp: 82
  mannte01:
    estimated: true
    gp: 82
  manntr01:
    estimated: true
    gp: 82
  manonch01:
    estimated: true
    gp: 82
  markkla01:
    estimated: true
    gp: 82
  marshna01:
    estimated: true
    gp: 82
  martial01:
    estimated: true
    gp: 82
  martica02:
    estimated: true
    gp: 82
  mashaja01:
    estimated: true
    gp: 82
  matkoka01:
    estimated: true
    gp: 82
  maxeyty01:
    estimated: true
    gp: 82
  mcbrimi01:
    estimated: true
    gp: 82
  mccaija01:
    estimated: true
    gp: 82
  mccolcj01:
    estimated: true
    gp: 82
  mccontj01:
    estimated: true
    gp: 82
  mcdanja02:
    estimated: true
    gp: 82
  mcgowbr01:
    estimated: true
    gp: 82
  mclaujo01:
    estimated: true
    gp: 82
  mcneeli01:
    estimated: true
    gp: 82
  meltode01:
    estimated: true
    gp: 82
  merrisa01:
    estimated: true
    gp: 82
  middlkh01:
    estimated: true
    gp: 82
  millebr02:
    estimated: true
    gp: 82
  millejo02:
    estimated: true
    gp: 82
  millele01:
    estimated: true
    gp: 82
  minixri01:
    estimated: true
    gp: 82
  minotjo01:
    estimated: true
    gp: 82
  missiyv01:
    estimated: true
    gp: 82
  mitchaj01:
    estimated: true
    gp: 82
  mitchda01:
    estimated: true
    gp: 82
  mitchdo01:
    estimated: true
    gp: 82
  mobleev01:
    estimated: true
    gp: 82
  mogbojo01:
    estimated: true
    gp: 82
  monkma01:
    estimated: true
    gp: 82
  moodymo01:
    estimated: true
    gp: 82
  moralal01:
    estimated: true
    gp: 82
  moranja01:
    estimated: true
    gp: 82
  murphtr02:
    estimated: true
    gp: 82
  murraco01:
    estimated: true
    gp: 82
  murrade01:
    estimated: true
    gp: 82
  murraja01:
    estimated: true
    gp: 82
  murrake02:
    estimated: true
    gp: 82
  murrakr01:
    estimated: true
    gp: 82
  mykhasv01:
    estimated: true
    gp: 82
  nancela02:
    estimated: true
    gp: 82
  nancepe01:
    estimated: true
    gp: 82
  nelsogr02:
    estimated: true
    gp: 82
  nembhan01:
    estimated: true
    gp: 82
  nembhry01:
    estimated: true
    gp: 82
  nesmiaa01:
    estimated: true
    gp: 82
  newelas01:
    estimated: true
    gp: 82
  niangge01:
    estimated: true
    gp: 82
  nnajize01:
    estimated: true
    gp: 82
  nurkiju01:
    estimated: true
    gp: 82
  okogijo01:
    estimated: true
    gp: 82
  okongon01:
    estimated: true
    gp: 82
  okorois01:
    estimated: true
    gp: 82
  onealro01:
    estimated: true
    gp: 82
  oubreke01:
    estimated: true
    gp: 82
  paytoga02:
    estimated: true
    gp: 82
  pedulse01:
    estimated: true
    gp: 82
  pendano01:
    estimated: true
    gp: 82
  phillju01:
    estimated: true
    gp: 82
  pippesc02:
    estimated: true
    gp: 82
  plowdda01:
    estimated: true
    gp: 82
  podzibr01:
    estimated: true
    gp: 82
  poeltja01:
    estimated: true
    gp: 82
  poolejo01:
    estimated: true
    gp: 82
  portecr01:
    estimated: true
    gp: 82
  porteke02:
    estimated: true
    gp: 82
  portemi01:
    estimated: true
    gp: 82
  portibo01:
    estimated: true
    gp: 82
  porzikr01:
    estimated: true
    gp: 82
  postqu01:
    estimated: true
    gp: 82
  pottemi01:
    estimated: true
    gp: 82
  poulajo01:
    estimated: true
    gp: 82
  poweldr01:
    estimated: true
    gp: 82
  powelno01:
    estimated: true
    gp: 82
  princta02:
    estimated: true
    gp: 82
  pritcpa01:
    estimated: true
    gp: 82
  proctty01:
    estimated: true
    gp: 82
  prospol01:
    estimated: true
    gp: 82
  pullizy01:
    estimated: true
    gp: 82
  queende01:
    estimated: true
    gp: 82
  quetane01:
    estimated: true
    gp: 82
  quickim01:
    estimated: true
    gp: 82
  randlju01:
    estimated: true
    gp: 82
  raynama01:
    estimated: true
    gp: 82
  reaveau01:
    estimated: true
    gp: 82
  reedpa01:
    estimated: true
    gp: 82
  reidna01:
    estimated: true
    gp: 82
  richaja02:
    estimated: true
    gp: 82
  richani01:
    estimated: true
    gp: 82
  richawi02:
    estimated: true
    gp: 82
  rileywi01:
    estimated: true
    gp: 82
  risacza01:
    estimated: true
    gp: 82
  robindu01:
    estimated: true
    gp: 82
  robinmi01:
    estimated: true
    gp: 82
  rolliry01:
    estimated: true
    gp: 82
  ruperra01:
    estimated: true
    gp: 82
  ryanco01:
    estimated: true
    gp: 82
  sabondo01:
    estimated: true
    gp: 82
  salauti01:
    estimated: true
    gp: 82
  sandeko01:
    estimated: true
    gp: 82
  santogu01:
    estimated: true
    gp: 82
  sarafbe01:
    estimated: true
    gp: 82
  sarral01:
    estimated: true
    gp: 82
  sassema01:
    estimated: true
    gp: 82
  scheiba01:
    estimated: true
    gp: 82
  sengual01:
    estimated: true
    gp: 82
  sensabr01:
    estimated: true
    gp: 82
  sextoco01:
    estimated: true
    gp: 82
  shamela01:
    estimated: true
    gp: 82
  shannte01:
    estimated: true
    gp: 82
  sharpda01:
    estimated: true
    gp: 82
  sharpsh01:
    estimated: true
    gp: 82
  sheadja01:
    estimated: true
    gp: 82
  sheppbe01:
    estimated: true
    gp: 82
  sheppre01:
    estimated: true
    gp: 82
  siakapa01:
    estimated: true
    gp: 82
  simonan01:
    estimated: true
    gp: 82
  simpskj01:
    estimated: true
    gp: 82
  simsje01:
    estimated: true
    gp: 82
  slawsja01:
    estimated: true
    gp: 82
  smallja01:
    estimated: true
    gp: 82
  smartma01:
    estimated: true
    gp: 82
  smithdr01:
    estimated: true
    gp: 82
  smithja04:
    estimated: true
    gp: 82
  smithja05:
    estimated: true
    gp: 82
  smithma02:
    estimated: true
    gp: 82
  smithto05:
    estimated: true
    gp: 82
  sochaje01:
    estimated: true
    gp: 82
  spencca01:
    estimated: true
    gp: 82
  spencpa01:
    estimated: true
    gp: 82
  stewais01:
    estimated: true
    gp: 82
  strawju01:
    estimated: true
    gp: 82
  suggsja01:
    estimated: true
    gp: 82
  tateja01:
    estimated: true
    gp: 82
  tatumja01:
    estimated: true
    gp: 82
  terryda01:
    estimated: true
    gp: 82
  thierad01:
    estimated: true
    gp: 82
  thompam01:
    estimated: true
    gp: 82
  thompau01:
    estimated: true
    gp: 82
  thompkl01:
    estimated: true
    gp: 82
  thybuma01:
    estimated: true
    gp: 82
  tomlina01:
    estimated: true
    gp: 82
  tonjejo01:
    estimated: true
    gp: 82
  topicni01:
    estimated: true
    gp: 82
  toppiob01:
    estimated: true
    gp: 82
  townska01:
    estimated: true
    gp: 82
  traorno01:
    estimated: true
    gp: 82
  trentga02:
    estimated: true
    gp: 82
  tshieos01:
    estimated: true
    gp: 82
  turnemy01:
    estimated: true
    gp: 82
  tysonja01:
    estimated: true
    gp: 82
  vandeja01:
    estimated: true
    gp: 82
  vanvlfr01:
    estimated: true
    gp: 82
  vassede01:
    estimated: true
    gp: 82
  vucevni01:
    estimated: true
    gp: 82
  vukcetr01:
    estimated: true
    gp: 82
  wadede01:
    estimated: true
    gp: 82
  wagnefr01:
    estimated: true
    gp: 82
  wagnemo01:
    estimated: true
    gp: 82
  walkeja01:
    estimated: true
    gp: 82
  walkeja02:
    estimated: true
    gp: 82
  wallaca01:
    estimated: true
    gp: 82
  walshjo01:
    estimated: true
    gp: 82
  walteja01:
    estimated: true
    gp: 82
  wareke01:
    estimated: true
    gp: 82
  washipj01:
    estimated: true
    gp: 82
  watfotr01:
    estimated: true
    gp: 82
  watkija01:
    estimated: true
    gp: 82
  watsope01:
    estimated: true
    gp: 82
  wellsja01:
    estimated: true
    gp: 82
  wembavi01:
    estimated: true
    gp: 82
  whiteco01:
    estimated: true
    gp: 82
  whitede01:
    estimated: true
    gp: 82
  wiggiaa01:
    estimated: true
    gp: 82
  wiggian01:
    estimated: true
    gp: 82
  william01:
    estimated: true
    gp: 82
  willibr03:
    estimated: true
    gp: 82
  willico04:
    estimated: true
    gp: 82
  willija06:
    estimated: true
    gp: 82
  willija07:
    estimated: true
    gp: 82
  willike04:
    estimated: true
    gp: 82
  willima07:
    estimated: true
    gp: 82
  willipa01:
    estimated: true
    gp: 82
  williro04:
    estimated: true
    gp: 82
  willizi01:
    estimated: true
    gp: 82
  willizi02:
    estimated: true
    gp: 82
  wilsoja03:
    estimated: true
    gp: 82
  wolfda01:
    estimated: true
    gp: 82
  youngch01:
    estimated: true
    gp: 82
  youngtr01:
    estimated: true
    gp: 82
  zikarro01:
    estimated: true
    gp: 82
  zubaciv01:
    estimated: true
    gp: 82
